# Configuración inicial para obtener el certificado SSL
server {
    listen 80;
    server_name fjpereirab.duckdns.org;

    # Ruta para la verificación de Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirigimos todo el tráfico HTTP a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name fjpereirab.duckdns.org;

    # Certificados SSL generados por Certbot
    ssl_certificate /etc/letsencrypt/live/fjpereirab.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fjpereirab.duckdns.org/privkey.pem;

    # Redirigimos las peticiones al contenedor PHP
    location / {
        proxy_pass http://aplicacion_tiempo;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}